# Generated by Django 4.2 on 2023-05-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addProblem',
        ),
    ]
