# Generated by Django 4.2 on 2023-05-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_addproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='addProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemNumber', models.IntegerField(max_length=100)),
                ('problemName', models.CharField(max_length=500)),
                ('problemDifficulty', models.CharField(max_length=10)),
                ('problemDescription', models.CharField(max_length=5000)),
            ],
        ),
    ]
