# Generated by Django 4.2 on 2023-05-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addProblem',
            new_name='Problem',
        ),
    ]
