# Generated by Django 4.2 on 2023-05-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
    ]
