# Generated by Django 4.2 on 2023-05-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_delete_user_submission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.AddField(
            model_name='submission',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problemNumber',
            field=models.IntegerField(verbose_name=100),
        ),
    ]
