# Generated by Django 4.2 on 2023-07-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_submission_langauge_remove_submission_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user_code',
            field=models.CharField(max_length=50),
        ),
    ]
