# Generated by Django 4.2 on 2023-07-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_submission_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user_code',
            field=models.CharField(max_length=10000),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
