# Generated by Django 4.2 on 2023-07-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_submission_user_code_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_name',
            field=models.CharField(default='easy', max_length=400),
        ),
    ]
