# Generated by Django 4.2 on 2023-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_submission_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user_name',
            field=models.CharField(max_length=400),
        ),
    ]
