# Generated by Django 4.2 on 2023-07-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_testcases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='user_code',
        ),
        migrations.AddField(
            model_name='submission',
            name='langauge',
            field=models.CharField(default='Java', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='result',
            field=models.CharField(default='FAILED', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
