# Generated by Django 4.2 on 2023-07-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_user_alter_submission_user_name_delete_newuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='user_name',
            new_name='user',
        ),
    ]
